enable_os_tools_install: true
enable_k3s_install: false
enable_offline_apt_repo: false
enable_apt_install: false
enable_drivers_install: false
enable_gpu_driver_uninstall: false
enable_network_setup: false
enable_docker_load: false
enable_helm_install: false
enable_netplan_config: false
